Repository Lekuruu/snowflake, pull requests merged in 2024-03, with the labels that each got.

#14 Refactor dockerfile to be dependent on volumes
  Dockerfile
Labels: code quality

#15 Implement tusk battle
  README.md
  app/engine/cards.py
  app/engine/game.py
  app/engine/grid.py
  app/engine/matchmaking.py
  app/engine/tusk.py
  app/handlers/login.py
  app/handlers/windows/manager.py
  app/objects/collections.py
  app/objects/effects.py
  app/objects/enemies.py
  app/objects/gameobject.py
  app/objects/ninjas.py
  app/objects/target.py
  app/server.py
Labels: feature, gameplay

#20 Add database name configuration
  .env_example
  app/data/postgres.py
  app/session.py
  config.py
Labels: enhancement

#19 Refactor policy server configuration
  .env_example
  config.py
  main.py
Labels: code quality, enhancement

#21 Fix "Heal 15" stamp
  app/engine/game.py
  app/objects/ninjas.py
Labels: bug, gameplay

#22 Adjust snow & water power beams
  app/engine/cards.py
  app/objects/effects.py
Labels: enhancement, visual

#28 Refactor exp calculations
  app/data/constants.py
  app/engine/game.py
  app/engine/tusk.py
  app/objects/enemies.py
  main.py
Labels: feature

#32 fix looping issue on win animations
  app/objects/ninjas.py
Labels: visual

#31 Matchmaking improvements
  app/engine/matchmaking.py
Labels: feature, enhancement

#33 Hide disconnected ninjas after round ends
  app/engine/game.py
Labels: bug, visual

#36 Remove snow gem from rewards list to fix sensei popup
  app/data/constants.py
Labels: bug

#37 Implement session token verification
  .env_example
  app/handlers/login.py
  config.py
Labels: enhancement
