Repository Lekuruu/snowflake, pull requests merged in 2024-02, with the labels that each got.

#3 Implement stamps
  .env_example
  README.md
  app/data/objects.py
  app/data/repositories/stamps.py
  app/engine/cards.py
  app/engine/game.py
  app/engine/penguin.py
  app/objects/ninjas.py
  config.py
Labels: enhancement

#6 Add beta mode
  .env_example
  .github/swf/cardjitsu_snowpayoutbeta.swf
  .github/swf/cardjitsu_snowplayerselectbeta.swf
  .github/swf/cjsnow_playerselectassetsbeta.swf
  .github/swf/cjsnow_uiassetsbeta.swf
  README.md
  app/engine/matchmaking.py
  app/handlers/windows/manager.py
  config.py
Labels: enhancement

#4 Add revive splash animation
  .github/swf/cardjitsu_snowrevive.swf
  app/engine/game.py
Labels: enhancement

#7 Actually add Beta Mode
  app/engine/game.py
Labels: enhancement

#12 Add `cardjitsu_snowrevive.swf` setup instructions
  README.md
Labels: documentation

#13 Implement double coins
  app/data/constants.py
  app/data/repositories/stamps.py
  app/engine/game.py
Labels: feature, gameplay
